// lib/cuisines.ts
// Viele in CH/EU gut erhältliche Küchen – erste Option ist der Auto/Default-Wert:
export const cuisines: string[] = [
  "Alle Küchen",
  "Schweizerisch",
  "Deutsch",
  "Österreichisch",
  "Italienisch",
  "Französisch",
  "Spanisch",
  "Portugiesisch",
  "Britisch/Irisch",
  "Skandinavisch",
  "Balkan",
  "Griechisch",
  "Türkisch",
  "Arabisch/Levantinisch",
  "Persisch/Iranisch",
  "Nordafrikanisch (Marokko/Tunesien/Algerien)",
  "Äthiopisch/Eritreisch",
  "Russisch/Osteuropäisch",
  "Indisch (Nord)",
  "Indisch (Süd)",
  "Pakistanisch",
  "Nepalesisch",
  "Sri-Lankisch",
  "Thai",
  "Vietnamesisch",
  "Chinesisch (Nord)",
  "Chinesisch (Süd/Kanton)",
  "Koreanisch",
  "Japanisch",
  "Indonesisch",
  "Malaysisch",
  "Philippinisch",
  "Mexikanisch",
  "Tex-Mex",
  "Peruanisch",
  "Argentinisch",
  "Brasilianisch",
  "Karibisch",
  "US-Amerikanisch",
  "Cajun/Creole",
  "Fusion (nur wenn wirklich nötig)"
];
