// lib/pantry.ts
import { uniqueSorted } from "@/lib/utils";

export const pantryGroups: { label: string; items: string[] }[] = [
  {
    label: "Grundnahrungsmittel",
    items: uniqueSorted([
      "Salz",
      "Pfeffer schwarz",
      "Zucker",
      "Zucker (Alternative, zuckerfrei)",
      "Honig",
      "Backpulver",
      "Trockenhefe",
      "Natron",
      "Speisestärke",
      "Paniermehl",
      "Brühepulver (Gemüse)",
      "Brühepulver (Huhn)",
      "Tomatenmark",
      "Passata",
      "Dosentomaten",
      "Kokosmilch",
      "Essiggurken",
      "Silberzwiebeln",
      "Sauerkraut",
      "Kapern",
      "Oliven (schwarz)",
      "Oliven (grün)",
      "Erdnussbutter",
      "Tahini",
      "Senf",
      "Mayonnaise",
      "Ketchup",
      "Eier", // <= neu hierher verschoben
    ]),
  },
  {
    label: "Getreide & Körner",
    items: uniqueSorted([
      "Weizenmehl",
      "Dinkelmehl",
      "Roggenmehl",
      "Maismehl",
      "Grieß (Weizen)",
      "Grieß (Hartweizen)",
      "Polenta",
      "Haferflocken",
      "Bulgur",
      "Couscous",
      "Quinoa",
      "Buchweizen",
      "Gerste/Perlgraupen",
      "Glutenfreies Mehl",
      "Haferflocken (glutenfrei)",
    ]),
  },
  {
    label: "Reis",
    items: uniqueSorted([
      "Reis (Langkorn)",
      "Jasminreis",
      "Basmatireis",
      "Risottoreis (Arborio/Carnaroli)",
      "Rundkornreis (Sushi)",
      "Wildreis-Mischung",
    ]),
  },
  {
    label: "Nudeln & Pasta",
    items: uniqueSorted([
      "Spaghetti",
      "Penne",
      "Fusilli",
      "Rigatoni",
      "Tagliatelle",
      "Lasagneblätter",
      "Gnocchi (trocken)",
      "Reisnudeln",
      "Udon",
      "Soba",
      "Glutenfreie Pasta",
    ]),
  },
  {
    label: "Öle & Fette",
    items: uniqueSorted([
      "Olivenöl",
      "Sonnenblumenöl",
      "Rapsöl",
      "Erdnussöl",
      "Sesamöl",
      "Butter",
      "Ghee/Butterschmalz",
      "Kokosöl",
      "Vegane Butter",
    ]),
  },
  {
    label: "Essige & Säuren",
    items: uniqueSorted([
      "Weißweinessig",
      "Rotweinessig",
      "Apfelessig",
      "Balsamico",
      "Reisessig",
      "Zitronensaft",
      "Limettensaft",
      "Tamarinde",
      "Mirin",
      "Sherryessig",
    ]),
  },

  /* -----------------------------------------------------------
     MASSIV erweitert: Saucen, Pasten, Fermente & Würzgrundlagen
     ----------------------------------------------------------- */
  {
    label: "Würzen & Saucen",
    items: uniqueSorted([
      // Soja / Fermente
      "Sojasauce",
      "Sojasauce (glutenfrei)",
      "Tamari",
      "Dunkle Sojasauce",
      "Helle Sojasauce",
      "Miso hell",
      "Miso dunkel",
      "Schwarze Bohnenpaste (Doubanjiang)",
      "Schwarze Bohnen Knoblauchsauce",
      "Hoisin",
      "Kecap Manis (süße Sojasauce)",

      // Fisch/Meeres-Umami
      "Fischsauce",
      "Austernsauce",
      "Worcestersauce",

      // Chilipasten/Schärfe
      "Gochujang",
      "Sambal Oelek",
      "Sriracha",
      "Chili Crisp",
      "Harissa",
      "Ajvar (mild)",
      "Ajvar (scharf)",

      // Curry-Pasten (deutlich erweitert)
      "Rote Currypaste",
      "Grüne Currypaste",
      "Gelbe Currypaste",
      "Massaman-Currypaste",
      "Panang-Currypaste",
      "Madras-Currypaste",
      "Vindaloo-Paste",
      "Korma-Paste",
      "Tandoori-Paste",
      "Rendang-Paste",
      "Laksa-Paste",
      "Tom Yum-Paste",

      // Kräuter-/Würzsaucen
      "Pesto Genovese",
      "Pesto Rosso",
      "Chimichurri",
      "Salsa Verde",
      "Tahini-Sauce",
      "Teriyaki-Sauce",
      "Sweet-Chili-Sauce",
      "BBQ-Sauce",
      "Hühnerfond (Glas)",
      "Rinderfond (Glas)",
      "Gemüsefond (Glas)",
    ]),
  },

  /* -----------------------------------------------------------
     MASSIV erweitert: reine Gewürze & Mischungen
     ----------------------------------------------------------- */
  {
    label: "Gewürze",
    items: uniqueSorted([
      // Klassiker
      "Paprika edelsüß",
      "Paprika scharf",
      "Paprika geräuchert",
      "Chiliflocken",
      "Cayennepfeffer",
      "Pfeffer bunt",
      "Pfeffer weiß",
      "Kreuzkümmel (Cumin)",
      "Kümmel",
      "Koriandersamen",
      "Fenchelsamen",
      "Anis",
      "Sternanis",
      "Zimt",
      "Nelken",
      "Piment",
      "Muskat",
      "Macis (Muskatblüte)",
      "Lorbeer",
      "Kurkuma",
      "Ingwerpulver",
      "Knoblauchpulver",
      "Zwiebelpulver",
      "Selleriesalz",
      "Zitronenpfeffer",
      "Rauchsalz",
      "Vanilleschote",
      "Safran",
      "Saflor (Färberdistel)",

      // Indisch / Nahost
      "Garam Masala",
      "Madras Curry (pulver)",
      "Tikka-Masala-Mix",
      "Bockshornklee",
      "Bockshornkleeblätter (Kasuri Methi)",
      "Ajwain",
      "Schwarzkümmel (Nigella)",
      "Asafoetida (Hing)",
      "Amchur (Mango-Pulver)",
      "Anardana (Granatapfelkerne, getrocknet)",
      "Chaat Masala",
      "Sumach",
      "Zaatar",
      "Baharat",
      "Ras el Hanout",
      "Dukkah",
      "Schawarma-Gewürz",

      // Ostasien
      "Chinesisches Fünf-Gewürz",
      "Sansho-Pfeffer",
      "Shichimi Togarashi",
      "Furikake",

      // Europa / Welt
      "Italienische Kräuter",
      "Herbes de Provence",
      "Cajun-Gewürz",
      "Creole-Gewürz",
      "BBQ Rub (klassisch)",
      "Gyros-Gewürz",
      "Brathähnchen-Gewürz",
      "Bratkartoffel-Gewürz",
      "Lebkuchengewürz",
      "Pumpkin Spice",
      "Zimtblüte (Kassiablüte)",
      "Pfeffer grün",
      "Pfeffer lang",
      "Kakaonibs (zum Würzen)",
      "Mohn (ganz)",
      "Senfkörner",
      "Kaperpulver",
      "Rote-Bete-Pulver",
    ]),
  },

  {
    label: "Frische Kräuter & Basics",
    items: uniqueSorted([
      "Petersilie",
      "Schnittlauch",
      "Basilikum",
      "Thymian",
      "Rosmarin",
      "Koriandergrün",
      "Minze",
      "Dill",
      "Frühlingszwiebeln",
      "Knoblauch",
      "Ingwer frisch",
      "Zwiebeln",
      "Schalotten",
      "Zitronengras",
      "Chili frisch",
      "Curryblätter (getrocknet)",
      "Zitrone",
      "Limette",
    ]),
  },
  {
    label: "Milchprodukte & Alternativen",
    items: uniqueSorted([
      "Milch",
      "Milch (laktosefrei)",
      "Sahne/Rahm",
      "Joghurt natur",
      "Joghurt (laktosefrei)",
      "Quark/Topfen",
      "Crème fraîche",
      "Parmesan",
      "Mozzarella",
      "Feta",
      "Gruyère",
      "Frischkäse",
      "Pflanzendrink (Soja)",
      "Pflanzendrink (Hafer)",
      "Pflanzendrink (Mandel)",
      "Vegane Sahne",
      "Veg. Reibekäse",
    ]),
  },
  {
    label: "Backen & Süßes",
    items: uniqueSorted([
      "Vanillezucker",
      "Kakaopulver",
      "Schokolade dunkel",
      "Schokolade Vollmilch",
      "Kokosraspel",
      "Mandelblättchen",
      "Haselnüsse gemahlen",
      "Rosinen",
      "Gelatine",
      "Agar-Agar",
      "Puderzucker",
      "Sirup (Ahorn/Agave)",
    ]),
  },
  {
    label: "Beilagen & Vorrat (frisch/TK)",
    items: uniqueSorted([
      "Kartoffeln festkochend",
      "Kartoffeln mehlig",
      "Süßkartoffeln",
      "Karotten",
      "Sellerieknolle",
      "Staudensellerie",
      "Champignons",
      "Paprika rot",
      "Paprika gelb",
      "Gurken",
      "Spinat",
      "Erbsen (TK)",
      "Mais (Dose)",
    ]),
  },
];
